# theme = "solarized-dark"
theme = "plain"
icons = "awesome5pro"

[[block]]
block = "weather"
format = "{weather} {temp}°, {wind} m/s {direction}"
service = { name = "openweathermap", api_key = "e78e47e391f6ee4595469febe9ba6dca", city_id = "498817", units = "metric" }

[[block]]
block = "net"
device = "enp3s0"

[[block]]
block = "memory"
format_mem = "{Mum}MB/{MTm}MB({Mup}%)"
format_swap = "{SUm}MB/{STm}MB({SUp}%)"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{max}°"

# [[block]]
# block = "load"
# interval = 1
# format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 10
format = "%a %d/%m %R"
